### ISSUE TITLE
I read your blog sounds nice. Is this the 1.9.x version? Modman not working

### ISSUE THREAD

**Issue by seansan** [ericthehacker/magento-configscopehints#11]
Seems like there is some reference to the Mage 2.x version?

 modman clone https://github.com/ericthehacker/magento2-configscopehints.git
Initialized empty Git repository in /home/dev/domains/mysite.nl/public_html/.modman/magento2-configscopehints/.git/
remote: Counting objects: 44, done.
remote: Total 44 (delta 0), reused 0 (delta 0), pack-reused 43
Unpacking objects: 100% (44/44), done.
ERROR: magento2-configscopehints does not contain a "modman" module description file.
Error trying to clone new module 'magento2-configscopehints', operation cancelled.

**Comment by ericthehacker** [comment]
@seansan 
This is the 1.X version of the module, so it shouldn't be referencing the Magento 2 version ...

If you copy the commands in the [installation section of the readme](https://github.com/ericthehacker/magento-configscopehints#installation) you should be good to go -- it has the correct modman URL.
